---
# defaults file for ansible-docker-engine-role

# Place to get apt repository key
apt_key_url: https://apt.dockerproject.org/gpg
# apt repository key signature
apt_key_sig: 2C52609D

# Name of the apt repository for docker
apt_repository: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main

# docker-engine is the default package name
docker_pkg_name: docker-engine
docker_apt_cache_valid_time: 600

# Set to 'yes' or 'true' to enable updates (sets 'latest' in apt module)
update_docker_package: no

kernel_pkg_state: latest

docker_compose_version: 1.7.1
